cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/php'

brew 'colordiff'
brew 'coreutils'
brew 'curl'
brew 'git'
brew 'go'
brew 'docker'
brew 'hugo'
brew 'node'
brew 'homebrew/php/composer'
brew 'homebrew/php/php70'
brew 'homebrew/php/php70-amqp'
brew 'homebrew/php/php70-ast'
brew 'homebrew/php/php70-intl'
brew 'homebrew/php/php70-mcrypt'
brew 'homebrew/php/php70-opcache'
brew 'homebrew/php/php70-redis', args: ['HEAD']
brew 'homebrew/php/php70-xdebug'
brew 'readline'
brew 'subversion'
brew 'tree'
brew 'openssl'
brew 'unrar'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'


cask '1password'
cask 'alfred'
cask 'atom'
cask 'bettertouchtool'
cask 'caffeine'
cask 'calibre'
cask 'dockertoolbox'
cask 'dropbox'
cask 'evernote'
cask 'filezilla'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'macdown'
cask 'phpstorm'
cask 'sequel-pro'
cask 'slack'
cask 'skype'
cask 'spotify'
cask 'tunnelblick'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
