cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'colordiff'
brew 'composer'
brew 'coreutils'
brew 'cocoapods'
brew "csvkit"
brew "curl"
brew 'docker'
brew 'esptool'
brew 'ffmpeg'
brew "firebase-cli"
brew 'git'
brew 'go'
brew 'hugo'
brew 'jq'
brew 'node'
brew 'php'
brew 'shellcheck'
brew "telnet"
brew "terraform"
brew 'tree'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'adobe-acrobat-reader'
cask 'android-studio'
cask 'alfred'
cask 'caffeine'
cask 'docker'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'grammarly'
cask 'iterm2'
cask 'keka'
cask 'mysqlworkbench'
cask 'remember-the-milk'
cask 'sequel-pro'
cask 'spotify'
cask 'slack'
cask 'telegram'
cask 'tunnelblick'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'

# 'mas install'
mas "Magnet", id: 441258766